In [1]:
# import stock_info module from yahoo_fin
from yahoo_fin import stock_info as si
import pandas as pd

In [2]:
stock_df = pd.read_csv("stock_list.csv")

In [3]:
def find_min_price(ticker,start = "01-01-2020", end = pd.Timestamp('today')):
    '''a function to find the lowest stock price'''
    df1 = si.get_data(ticker,start_date = start, end_date = end, index_as_date=True)
    return df1[df1.close == df1.close.min()]

In [4]:
'''returns a dataframe of all the lowest prices given a stock list.'''
df3=pd.DataFrame(columns=['open','high','low','close','adjclose','volume','ticker'])
for ticker in stock_df.Ticker:
    res = find_min_price(ticker)   
    df3 = df3.append(res)

In [5]:
def find_price_ondate(ticker,d,n=1):
    '''to find the stock price given a ticer and a date. Data range is optional. Default is 1 day.'''
    d = pd.Timestamp(d)
    try:
        res = si.get_data(ticker,start_date = d, end_date = d + pd.tseries.offsets.DateOffset(n), index_as_date=True)
    except KeyError:
        res = "Not a trading day. Please enter a different date."
    return res

In [6]:
#replace the ticker and date below to find the lowest stock price givens the date range.

find_min_price("amzn","01-01-2007")

                 open       high    low      close   adjclose    volume ticker
2008-11-20  35.290001  39.720001  34.68  35.029999  35.029999  18423900   AMZN

In [7]:
#replace the ticker and date below to find the stock price for that day.
find_price_ondate("goog", "01-01-2020",60)

,open,high,low,close,adjclose,volume,ticker
2020-01-02,1341.550049,1368.140015,1341.550049,1367.369995,1367.369995,1406600,GOOG
2020-01-03,1347.859985,1372.500000,1345.543945,1360.660034,1360.660034,1186400,GOOG
2020-01-06,1350.000000,1396.500000,1350.000000,1394.209961,1394.209961,1732300,GOOG
2020-01-07,1397.939941,1402.989990,1390.380005,1393.339966,1393.339966,1502700,GOOG
2020-01-08,1392.079956,1411.579956,1390.839966,1404.319946,1404.319946,1528000,GOOG
2020-01-09,1420.569946,1427.329956,1410.270020,1419.829956,1419.829956,1500900,GOOG
2020-01-10,1427.560059,1434.928955,1418.349976,1429.729980,1429.729980,1820700,GOOG
2020-01-13,1436.130005,1440.520020,1426.020020,1439.229980,1439.229980,1652300,GOOG
2020-01-14,1439.010010,1441.800049,1428.369995,1430.880005,1430.880005,1558900,GOOG
2020-01-15,1430.209961,1441.395020,1430.209961,1439.199951,1439.199951,1282700,GOOG
2020-01-16,1447.439941,1451.989990,1440.920044,1451.699951,1451.699951,1173700,GOOG
2020-01-17,1462.910034,1481.295044,1458.219971,1480.390015,1480.390015,2396200,GOOG
2020-01-21,1479.119995,1491.849976,1471.199951,1484.400024,1484.400024,2036700,GOOG
2020-01-22,1491.000000,1503.213989,1484.930054,1485.949951,1485.949951,1610800,GOOG
2020-01-23,1487.640015,1495.520020,1482.099976,1486.650024,1486.650024,1351200,GOOG
2020-01-24,1493.589966,1495.494995,1465.250000,1466.709961,1466.709961,1784600,GOOG
2020-01-27,1431.000000,1438.069946,1421.199951,1433.900024,1433.900024,1755200,GOOG
2020-01-28,1443.000000,1456.000000,1432.469971,1452.560059,1452.560059,1577400,GOOG
2020-01-29,1458.800049,1465.430054,1446.739990,1458.630005,1458.630005,1077700,GOOG
2020-01-30,1439.959961,1457.280029,1436.400024,1455.839966,1455.839966,1339400,GOOG
2020-01-31,1468.900024,1470.130005,1428.530029,1434.229980,1434.229980,2417200,GOOG
2020-02-03,1462.000000,1490.000000,1458.989990,1485.939941,1485.939941,3055200,GOOG
2020-02-04,1457.069946,1469.500000,1426.300049,1447.069946,1447.069946,3933000,GOOG
2020-02-05,1462.420044,1463.839966,1430.560059,1448.229980,1448.229980,1986200,GOOG
2020-02-06,1450.329956,1482.000000,1449.569946,1476.229980,1476.229980,1679400,GOOG
2020-02-07,1467.300049,1485.839966,1466.349976,1479.229980,1479.229980,1172300,GOOG
2020-02-10,1474.319946,1509.500000,1474.319946,1508.680054,1508.680054,1419900,GOOG
2020-02-11,1511.810059,1529.630005,1505.637939,1508.790039,1508.790039,1344600,GOOG
2020-02-12,1514.479980,1520.694946,1508.109985,1518.270020,1518.270020,1167600,GOOG
2020-02-13,1512.689941,1527.180054,1504.599976,1514.660034,1514.660034,929500,GOOG
2020-02-14,1515.599976,1520.739990,1507.339966,1520.739990,1520.739990,1197800,GOOG
2020-02-18,1515.000000,1531.630005,1512.589966,1519.670044,1519.670044,1120700,GOOG
2020-02-19,1525.069946,1532.105957,1521.400024,1526.689941,1526.689941,949300,GOOG
2020-02-20,1522.000000,1529.640015,1506.819946,1518.150024,1518.150024,1096600,GOOG
2020-02-21,1508.030029,1512.214966,1480.439941,1485.109985,1485.109985,1731700,GOOG
2020-02-24,1426.109985,1436.969971,1411.390015,1421.589966,1421.589966,2867100,GOOG
2020-02-25,1433.000000,1438.140015,1382.400024,1388.449951,1388.449951,2478300,GOOG
2020-02-26,1396.140015,1415.699951,1379.000000,1393.180054,1393.180054,2202400,GOOG
2020-02-27,1362.060059,1371.703979,1317.170044,1318.089966,1318.089966,2978300,GOOG
2020-02-28,1277.500000,1341.140015,1271.000000,1339.329956,1339.329956,3790600,GOOG

In [11]:
df_all =pd.DataFrame(columns=['open','high','low','close','adjclose','volume','ticker'])
for ticker in stock_df.Ticker:
    res = find_price_ondate(ticker, "01-01-2020",365)
    df_all = df_all.append(res)

,open,high,low,close,adjclose,volume,ticker
2020-01-02,11.370000,11.430000,10.980000,11.090000,11.090000,694700,DNOW
2020-01-03,11.140000,11.190000,10.820000,11.120000,11.120000,948700,DNOW
2020-01-06,11.230000,11.585000,11.190000,11.530000,11.530000,777700,DNOW
2020-01-07,11.480000,11.760000,11.420000,11.630000,11.630000,629000,DNOW
2020-01-08,11.550000,11.760000,11.465000,11.480000,11.480000,727900,DNOW
...,...,...,...,...,...,...,...
2020-03-27,359.089996,368.559998,353.000000,357.119995,357.119995,7948800,NFLX
2020-03-30,363.000000,377.799988,361.170013,370.959991,370.959991,8622000,NFLX
2020-03-31,367.929993,383.010010,366.440002,375.500000,375.500000,9366500,NFLX
2020-04-01,376.049988,380.230011,361.019989,364.079987,364.079987,6672500,NFLX
2020-04-02,364.079987,370.989990,360.059998,370.079987,370.079987,4586400,NFLX

In [8]:
# columns_name = ["ticker","quote_price", "52_week_range"]
# tickers = []
# prices = []
# high_low = []
# for ticker in stock_df.Ticker:
#     tickers.append(ticker)
#     prices.append(si.get_quote_table(ticker)["Quote Price"])
#     high_low.append(si.get_quote_table(ticker)["52 Week Range"])
# all_result_dict = {"ticker": tickers, "quote_price": prices, "52_week_range": high_low}
# all_result_df = pd.DataFrame(all_result_dict)

In [9]:
# all_result_df[['52_week_low','52_week_high']] = all_result_df["52_week_range"].str.split("-", expand = True)

In [10]:
# all_result_df = all_result_df.drop("52_week_range", axis=1)
# all_result_df.to_csv("stock_info.csv",index=False)

In [17]:
df_all.to_csv("stock_info2.csv",index_label= "Date")